# Generated by Django 5.2.8 on 2025-11-15 04:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Department Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grade_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Grade/Level Name"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=1, verbose_name="Display Order"),
                ),
            ],
            options={
                "verbose_name": "Employee Grade",
                "verbose_name_plural": "Employee Grades",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Region Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
            },
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scenario_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Scenario Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Scenario",
                "verbose_name_plural": "Scenarios",
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sector_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Sector Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sector",
                "verbose_name_plural": "Sectors",
            },
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Account Code"
                    ),
                ),
                (
                    "account_name",
                    models.CharField(max_length=255, verbose_name="Account Name"),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset"),
                            ("LIABILITY", "Liability"),
                            ("EQUITY", "Equity"),
                            ("REVENUE", "Revenue/Income"),
                            ("EXPENSE", "Expense"),
                        ],
                        max_length=50,
                        verbose_name="Account Type",
                    ),
                ),
                (
                    "statement_category",
                    models.CharField(
                        max_length=20, verbose_name="Statement Category (e.g., P&L, BS)"
                    ),
                ),
                (
                    "hierarchy_level_1",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Level 1"
                    ),
                ),
                (
                    "hierarchy_level_2",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Level 2"
                    ),
                ),
                (
                    "hierarchy_level_3",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Level 3"
                    ),
                ),
                (
                    "hierarchy_level_4",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Level 4"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="Display Order"),
                ),
                (
                    "is_leaf",
                    models.BooleanField(default=True, verbose_name="Is Leaf Node"),
                ),
                (
                    "active_flag",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "parent_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="budgeting.account",
                        verbose_name="Parent Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account (Chart of Account)",
                "verbose_name_plural": "Accounts (Chart of Accounts)",
                "ordering": ["account_code"],
            },
        ),
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fund_type",
                    models.CharField(
                        choices=[
                            ("MUTUAL", "Mutual Funds"),
                            ("RSA", "RSA Funds (PENCOM)"),
                        ],
                        max_length=50,
                        verbose_name="Fund Type",
                    ),
                ),
                (
                    "fund_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Fund Name"
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        max_length=100,
                        verbose_name="Category Name (e.g., Active/Balanced)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fund",
                "verbose_name_plural": "Funds",
                "unique_together": {("fund_type", "fund_name")},
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "phone_no",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="budgeting.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="budgeting.grade",
                        verbose_name="Grade/Level",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="State Name"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="states",
                        to="budgeting.region",
                        verbose_name="Region",
                    ),
                ),
            ],
            options={
                "verbose_name": "State",
                "verbose_name_plural": "States",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Location Name"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="budgeting.region",
                        verbose_name="Region",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="budgeting.state",
                        verbose_name="State",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location (Branch)",
                "verbose_name_plural": "Locations (Branches)",
            },
        ),
        migrations.CreateModel(
            name="GLTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField(verbose_name="Transaction Date")),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Description"),
                ),
                (
                    "transaction_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=18,
                        verbose_name="Transaction Amount",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=18,
                        verbose_name="Running Balance",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="budgeting.account",
                        verbose_name="GL Account",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="budgeting.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="budgeting.fund",
                        verbose_name="Fund",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="budgeting.scenario",
                        verbose_name="Scenario (e.g., ACTUAL)",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="budgeting.sector",
                        verbose_name="Sector",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="budgeting.state",
                        verbose_name="State",
                    ),
                ),
            ],
            options={
                "verbose_name": "GL Transaction",
                "verbose_name_plural": "GL Transactions",
            },
        ),
        migrations.CreateModel(
            name="FinancialRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(2000)],
                        verbose_name="Fiscal Year",
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Month",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=18,
                        verbose_name="Value",
                    ),
                ),
                (
                    "is_editable",
                    models.BooleanField(
                        default=False, verbose_name="Is Editable Forecast"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="budgeting.account",
                        verbose_name="GL Account",
                    ),
                ),
                (
                    "fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="budgeting.fund",
                        verbose_name="Fund",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="budgeting.scenario",
                        verbose_name="Scenario Type",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="budgeting.sector",
                        verbose_name="Sector",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="budgeting.state",
                        verbose_name="State",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Financial Record",
                "verbose_name_plural": "Monthly Financial Records",
                "ordering": ["year", "month"],
                "unique_together": {
                    ("account", "fund", "year", "month", "scenario", "state", "sector")
                },
            },
        ),
    ]
