# Generated by Django 5.2.8 on 2025-11-15 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgeting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Category Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fund Category",
                "verbose_name_plural": "Fund Categories",
                "ordering": ["category_name"],
            },
        ),
        migrations.RemoveField(
            model_name="fund",
            name="category_name",
        ),
        migrations.AddField(
            model_name="fund",
            name="fund_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="funds",
                to="budgeting.fundcategory",
                verbose_name="Fund Category",
            ),
        ),
    ]
