# Generated by Django 5.2.8 on 2025-11-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgeting", "0002_fundcategory_remove_fund_category_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateDimension",
            fields=[
                (
                    "full_date",
                    models.DateField(
                        primary_key=True, serialize=False, verbose_name="Full Date"
                    ),
                ),
                ("day", models.PositiveSmallIntegerField(verbose_name="Day")),
                (
                    "week_of_year",
                    models.PositiveSmallIntegerField(verbose_name="Week of Year"),
                ),
                ("month", models.PositiveSmallIntegerField(verbose_name="Month")),
                (
                    "month_name",
                    models.CharField(max_length=15, verbose_name="Month Name"),
                ),
                (
                    "short_month_name",
                    models.CharField(max_length=3, verbose_name="Short Month Name"),
                ),
                ("quarter", models.PositiveSmallIntegerField(verbose_name="Quarter")),
                (
                    "quarter_name",
                    models.CharField(max_length=10, verbose_name="Quarter Name"),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Year")),
                (
                    "year_month",
                    models.CharField(max_length=7, verbose_name="Year-Month (YYYY-MM)"),
                ),
                (
                    "year_quarter",
                    models.CharField(
                        max_length=7, verbose_name="Year-Quarter (YYYY-Q#)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Date Dimension",
                "verbose_name_plural": "Date Dimensions",
                "ordering": ["full_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="state",
            options={
                "ordering": ["state_name"],
                "verbose_name": "State",
                "verbose_name_plural": "States",
            },
        ),
        migrations.RemoveField(
            model_name="account",
            name="id",
        ),
        migrations.AddField(
            model_name="account",
            name="account_key",
            field=models.BigAutoField(
                primary_key=True, serialize=False, verbose_name="Account Key"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_name",
            field=models.CharField(max_length=100, verbose_name="Account Name"),
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("ASSET", "Asset"),
                    ("LIABILITY", "Liability"),
                    ("EQUITY", "Equity"),
                    ("REVENUE", "Revenue/Income"),
                    ("EXPENSE", "Expense"),
                ],
                max_length=20,
                verbose_name="Account Type",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="statement_category",
            field=models.CharField(
                max_length=30, verbose_name="Statement Category (e.g., P&L, BS)"
            ),
        ),
    ]
