# Generated by Django 5.2.7 on 2025-10-30 14:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DO", "Dept Officer"),
                            ("HOD", "Head of Department"),
                            ("AA", "App Admin"),
                            ("SA", "Super Admin"),
                        ],
                        default="DO",
                        max_length=3,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        help_text="User's assigned department for budgeting.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True by Admin upon final approval.",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the user has been approved by the App Admin.",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "permissions": [
                    ("can_upload_gl", "Can upload and map GL data"),
                    (
                        "can_approve_access",
                        "Can approve or reject user access requests",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Access Granted"),
                            ("REJECTED", "Access Denied"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "requested_role",
                    models.CharField(
                        choices=[
                            ("DO", "Dept Officer"),
                            ("HOD", "Head of Department"),
                            ("AA", "App Admin"),
                            ("SA", "Super Admin"),
                        ],
                        default="DO",
                        max_length=3,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection, sent to the user."
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The App Admin or Super Admin who took action.",
                        limit_choices_to={"role__in": ["AA", "SA"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user account requesting access.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_request",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Access Request",
                "verbose_name_plural": "User Access Requests",
                "ordering": ["requested_at"],
            },
        ),
    ]
